package info.ata4.disunity.cli.util;

import com.diffblue.deeptestutils.Reflector;
import info.ata4.disunity.cli.OutputFormat;
import info.ata4.disunity.cli.util.JsonTablePrinter;
import info.ata4.disunity.cli.util.TablePrinter;
import info.ata4.disunity.cli.util.TextTablePrinter;
import org.junit.Assert;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

import java.io.PrintWriter;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.nio.file.Path;

public class TablePrinterTest {

  @Rule public ExpectedException thrown = ExpectedException.none();

  /* testedClasses: TablePrinter */
  
  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire method.
   */

  @Test
  public void fromOutputFormatInputNotNullNullOutputNotNull() {

    // Arrange
    final OutputFormat format = OutputFormat.TEXT;
    final PrintWriter out = null;

    // Act
    final TablePrinter retval = TablePrinter.fromOutputFormat(format, out);

    // Assert result
    Assert.assertNotNull(retval);
    Assert.assertNull(((TextTablePrinter)retval).file);
    Assert.assertNull(((TextTablePrinter)retval).out);
    Assert.assertEquals('=', Reflector.getInstanceField(retval, "nameSeparator"));
    Assert.assertEquals('-', Reflector.getInstanceField(retval, "rowSeparator"));
    Assert.assertEquals("  ", Reflector.getInstanceField(retval, "cellSeparator"));
  }


  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers:
   *  - case 1 of switch on line 24
   */

  @Test
  public void fromOutputFormatInputNotNullNullOutputNotNull2() {

    // Arrange
    final OutputFormat format = OutputFormat.JSON;
    final PrintWriter out = null;

    // Act
    final TablePrinter retval = TablePrinter.fromOutputFormat(format, out);

    // Assert result
    Assert.assertNotNull(retval);
    Assert.assertNull(((JsonTablePrinter)retval).out);
    Assert.assertNull(((JsonTablePrinter)retval).file);
  }
  
}
