/*
 ** 2014 Mai 05
 **
 ** The author disclaims copyright to this source code.  In place of
 ** a legal notice, here is a blessing:
 **    May you do good and not evil.
 **    May you find forgiveness for yourself and forgive others.
 **    May you share freely, never taking more than you give.
 */
package info.ata4.unity.gui;

import info.ata4.log.LogUtils;
import info.ata4.unity.DisUnity;
import info.ata4.unity.gui.control.AssetFileTreeController;
import info.ata4.unity.gui.util.DialogUtils;
import info.ata4.unity.gui.util.FileExtensionFilter;
import info.ata4.unity.gui.view.AssetFileTreeCellRenderer;
import info.ata4.unity.rtti.FieldTypeDatabase;
import java.io.IOException;
import java.nio.file.Path;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author Nico Bergemann <barracuda415 at yahoo.de>
 */
public class DisUnityWindow extends javax.swing.JFrame {
    
    private static final Logger L = LogUtils.getLogger();
    
    private Path filePrevious;
    private AssetFileTreeController treeCtl;
    
    /**
     * Creates new form DisUnityWindow
     */
    public DisUnityWindow() {
        initComponents();
        initComponentsCustom();
    }
    
    private void initComponentsCustom() {
        // add custom filters
        openFileChooser.addChoosableFileFilter(new FileExtensionFilter("Unity scene", "unity"));
        openFileChooser.addChoosableFileFilter(new FileExtensionFilter("Unity asset bundle", "unity3d"));
        openFileChooser.addChoosableFileFilter(new FileExtensionFilter("Unity asset", "asset", "assets", "sharedAssets"));
        
        treeCtl = new AssetFileTreeController(this, dataTree, dataText);
    }
    
    public void loadFile(Path file) {
        filePrevious = file;
        
        try {
            treeCtl.load(file);
        } catch (IOException ex) {
            DialogUtils.exception(ex, "Error loading file " + file.getFileName());
            L.log(Level.WARNING, "Can't load file", ex);
        } catch (Exception ex) {
            DialogUtils.exception(ex, "Error loading file " + file.getFileName());
            L.log(Level.WARNING, "Can't set tree model", ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        openFileChooser = new javax.swing.JFileChooser();
        dataSplitPane = new javax.swing.JSplitPane();
        dataTreeScrollPane = new javax.swing.JScrollPane();
        dataTree = new javax.swing.JTree();
        dataTextScrollPane = new javax.swing.JScrollPane();
        dataText = new javax.swing.JTextPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        openTypeDatabaseItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(DisUnity.getSignature());

        dataSplitPane.setDividerLocation(300);

        dataTreeScrollPane.setViewportView(dataTree);

        dataSplitPane.setLeftComponent(dataTreeScrollPane);

        dataText.setEditable(false);
        dataText.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        dataTextScrollPane.setViewportView(dataText);

        dataSplitPane.setRightComponent(dataTextScrollPane);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        saveMenuItem.setEnabled(false);
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        saveAsMenuItem.setEnabled(false);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        jMenu1.setText("Tools");

        openTypeDatabaseItem.setText("Open type tree database");
        openTypeDatabaseItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openTypeDatabaseItemActionPerformed(evt);
            }
        });
        jMenu1.add(openTypeDatabaseItem);

        menuBar.add(jMenu1);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dataSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dataSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        if (filePrevious != null) {
            openFileChooser.setSelectedFile(filePrevious.toFile());
        }
        int result = openFileChooser.showOpenDialog(this);
        if (result != JFileChooser.APPROVE_OPTION) {
            return;
        }
        
        Path file = openFileChooser.getSelectedFile().toPath();
        loadFile(file);
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void openTypeDatabaseItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openTypeDatabaseItemActionPerformed
        treeCtl.load(FieldTypeDatabase.getInstance());
    }//GEN-LAST:event_openTypeDatabaseItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JSplitPane dataSplitPane;
    private javax.swing.JTextPane dataText;
    private javax.swing.JScrollPane dataTextScrollPane;
    private javax.swing.JTree dataTree;
    private javax.swing.JScrollPane dataTreeScrollPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JFileChooser openFileChooser;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem openTypeDatabaseItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

}
